---
- name: Crear OU y usuario AD
  hosts: windows
  gather_facts: no
  tasks:
    - name: Crear un usuario
      microsoft.ad.user:
        name: "jperez"
        firstname: "Juan"
        surname: "Perez"
        upn: "jperez@tagost.com"
        password: "Abcd.123"
        path: "CN=Users,DC=tagost,DC=com"
        state: present
        enabled: yes

