---
- name: Construir y subir EE con podman
  hosts: localhost
  gather_facts: false

  vars:
    #ee_directory: execution-environment         # Ruta al Dockerfile
    ee_image_local: ee-custom:latest                          # Nombre local
    ee_image_remote: ansible-aap.apps.power.ocp.local/ee-custom:latest

  tasks:
    - name: Mostrar playbook_dir
      debug:
        msg: "El playbook está en: {{ playbook_dir }}"

    - name: Login en el registry
      ansible.builtin.command: >
        podman login -u {{ registry_username }} -p {{ registry_password }} {{ ee_image_remote.split('/')[0] }} --tls-verify=false
      no_log: false

    - name: descargar imagen base
      ansible.builtin.command: >
        podman pull --tls-verify=false ansible-aap.apps.power.ocp.local/ansible-automation-platform-25/ee-minimal-rhel9:ppc64le
        podman pull --tls-verify=false ansible-aap.apps.power.ocp.local/ee-custom:latest
    
    - name: Construir imagen con podman
      ansible.builtin.command: >
        podman build -t {{ ee_image_local }} .
      #args:
      #  chdir: "{{ ee_directory }}"

    - name: Etiquetar imagen para el registry remoto
      ansible.builtin.command: >
        podman tag {{ ee_image_local }} {{ ee_image_remote }}

    - name: Push de la imagen al registry remoto
      ansible.builtin.command: >
        podman push {{ ee_image_remote }} --tls-verify=false

