FROM ansible-aap.apps.power.ocp.local/ansible-automation-platform-24/ee-minimal-rhel9:latest

# Instalar system dependencies si es necesario
RUN microdnf install -y \
      pip \
    && microdnf clean all

# Copiar requirements
COPY requirements.yaml /tmp/requirements.yaml
COPY requirements.txt /tmp/requirements.txt

# Instalar collections y pip packages
RUN ansible-galaxy collection install -r /tmp/requirements.yaml \
 && pip3 install --no-cache-dir -r /tmp/requirements.txt

USER ansible

