FROM registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel9:latest

# Instalar system dependencies si es necesario
RUN microdnf install -y \
      git \
      python3-pip \
    && microdnf clean all

# Copiar requirements
COPY requirements.yml /tmp/requirements.yml
COPY requirements.txt /tmp/requirements.txt

# Instalar collections y pip packages
RUN ansible-galaxy collection install -r /tmp/requirements.yml \
 && pip3 install --no-cache-dir -r /tmp/requirements.txt

USER ansible

